version: '3.9'

services:
  web:
    image: bwhite14/bwhiterepo:my-website
    container_name: expo_web_server
    restart: unless-stopped
    env_file: ".env"

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
