name: Build and Deploy

on:
  push:
    branches:
      - master  # or your deploy branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Get current Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S')"

        
      - name: Build and Push Docker Image
        run: |
          docker buildx build --platform linux/arm64 -t bwhite14/bwhiterepo:my-website --push .

      - name: Trigger app server webhook
        env:
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
          PAYLOAD: '{"event": "deploy"}'
        run: |
          SIGNATURE=$(echo -n "$PAYLOAD" | openssl dgst -sha256 -hmac "$SECRET" | sed 's/^.* //')
          curl -X POST "https://brysonw.net/webhook" |
          -H "Content-Type: application/json" \
          -H "X-Hub-Signature-256: sha256=$SIGNATURE" |
          -H "X-GitHub-Event: push" \
          -d "$PAYLOAD"
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "🚀 my-website Deployed"
          to: jonathanbrysonwhite@gmail.com
          from: deployer@brysonw.net
          body: |
            The latest image for `my-website` has been deployed.
            Time: ${{ steps.date.outputs.time }}
            Commit: ${{ github.sha }}
